name: Integración Continua Java

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código del repositorio
      uses: actions/checkout@v5 # Actualizado a v5

    - name: 2. Configurar el entorno de Java
      uses: actions/setup-java@v5 # Actualizado a v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 3. Ejecutar las pruebas unitarias con Maven Wrapper
      run: |
        chmod +x mvnw
        ./mvnw test